### ISSUE TITLE
Improve/setup CI/CD Github workflows

### ISSUE THREAD

**Issue by TorinFCSE** [CSE112-team1/CSE112-team1#11]
CI/CD Should
* run jest js tests
* validate html/css

**Comment by TorinFCSE** [comment]
The super linter they use validates html. I'll look deeper into the testing suit "Jest" and see if it's able to javascript tests that access the dom so we can test parts of the gui. We did this for android so it should be possible here too

**Comment by SeaScript1** [comment]
Solved through User Story Tasks
