### ISSUE TITLE
US 4-2: Create Fallback Responses

### ISSUE THREAD

**Issue by SeaScript1** [CSE112-team1/CSE112-team1#20]
In-case of AI failure, provide previously generated fallback responses

**Comment by TorinFCSE** [comment]
Ideas

- Cache generated fortunes, if AI is unavailable, select a randomly saved fortune and card combo to replace the users
- Create 1000 pregenerated daily fortunes using some low cost api

**Comment by SeaScript1** [comment]
The scope for this task changed of the course of the project. We are handling fallback responses with a client generated AI response in the scenario that our cloud function generated response is down.
